// resources/js/vuejs/components/inc/user/FooterUserSite.vue
<template>
    <footer class="footer footer-big bg-gradient-default">
        <div class="container">
            <div class="content">
                <div class="row mb-5">
                    <div class="column mr-auto">
                        <img src="/assets/vendor_site/img/brand/blue.png" class="logo logo-sm" alt="">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <div class="column">
                            <h4 class="mb-4">Presentation</h4>
                            <ul class="links-vertical">
                                <li>
                                    <router-link :to="{ name: 'about' }">
                                        A propos de nous
                                    </router-link>
                                </li>
                                <li>
                                    <a href="/concept">
                                        Notre concept
                                    </a>
                                </li>
                                <li>
                                    <router-link :to="{ name: 'faqs' }">
                                        Faq
                                    </router-link>
                                </li>
                                <li>
                                    <router-link :to="{ name: 'contact_cm' }">
                                        Contact
                                    </router-link>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="column">
                            <h4 class="mb-4">Services</h4>
                            <ul class="links-vertical">
                                <li>
                                    <a href="/services">
                                        Nos services
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        Media Kit
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="column">
                            <h4 class="mb-4">Informations</h4>
                            <ul class="links-vertical">
                                <li>
                                    <a href="javascript:;">
                                        Licence
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        Terme et Condition
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        Politique de confidentialite
                                    </a>
                                </li>
                                <li>
                                    <a href="javascript:;">
                                        Legale notice 
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="column">
                            <h4 class="mb-4">Newsletter</h4>
                            <ul class="links-vertical">
                                <p>We handpicked the most interesting content for you. No spam. It takes one click to unsubscribe. Give
                                    it a try!</p>
                                <form class="form form-newsletter" method="" action="">
                                    <div class="form-group">
                                        <input type="email" class="form-control" placeholder="Your Email">
                                    </div>
                                    <button type="button" class="btn btn-primary" name="button">
                                        Subscribe
                                    </button>
                                </form>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <hr class="bg-white opacity-3">
            <div class="col-md-3 mx-auto">
                <button type="button" class="btn-icon-only rounded-circle btn btn-facebook">
                    <span class="btn-inner--icon"><i class="fab fa-facebook"></i></span>
                </button>
                <button type="button" class="btn-icon-only rounded-circle btn btn-twitter">
                    <span class="btn-inner--icon"><i class="fab fa-twitter"></i></span>
                </button>
                <button type="button" class="btn-instagram btn-icon-only rounded-circle btn">
                    <span class="btn-inner--icon"><i class="fab fa-instagram"></i></span>
                </button>
                <button type="button" class="btn-icon-only rounded-circle btn btn-pinterest">
                    <span class="btn-inner--icon"><i class="fab fa-pinterest"></i></span>
                </button>
            </div>
        </div>
        <div class="copyright d-flex justify-content-center mt-4 mr-40">
            Copyright &copy; {{ new Date().getFullYear() }}. Realized by <a href="/" class="title-red" style="padding-left: 4px; color: red">KazouGroup srl</a></h6>
        </div>
    </footer>
</template>

<script>
    export default {
        name: "FooterUserSite"
    }
</script>

<style scoped>

</style>

// resources/js/reactjs/components/inc/FooterUserSite.jsx
import React, { Component } from "react";
import {Link} from 'react-router-dom';


class FooterUserSite extends Component {

    render() {

        return (
            <footer className="footer footer-big bg-gradient-default">
                <div className="container">
                    <div className="content">
                        <div className="row mb-5">
                            <div className="column mr-auto">
                                <img src=".." className="logo logo-sm" alt="Kazoutech" />
                            </div>
                        </div>
                        <div className="row">
                            <div className="col-md-2">
                                <div className="column">
                                    <h4 className="mb-4">Presentation</h4>
                                    <ul className="links-vertical">
                                        <li>
                                            <Link to={'/about/'}>
                                                A propos de nous
                                            </Link>
                                        </li>
                                        <li>
                                             <Link to={'/concept/'}>
                                                Notre concept
                                            </Link>
                                        </li>
                                        <li>
                                            <Link to={'/faqs/'}>
                                                Faq
                                            </Link>
                                        </li>
                                        <li>
                                            <Link to={'/contacts/'}>
                                                Contacts
                                            </Link>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div className="col-md-2">
                                <div className="column">
                                    <h4 className="mb-4">Services</h4>
                                    <ul className="links-vertical">
                                        <li>
                                        <Link to={'/occupations/'}>
                                                Nos categorie
                                        </Link>
                                        </li>
                                        <li>
                                            <Link to={'/annonces/'}>
                                               Annonces
                                            </Link>
                                        </li>
                                        <li>
                                            <Link to={'/blog/'}>
                                                Blog
                                            </Link>
                                        </li>
                                        <li>
                                            <Link to={'/temoignages/'}>
                                                Temoignages
                                            </Link>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div className="col-md-3">
                                <div className="column">
                                    <h4 className="mb-4">Informations</h4>
                                    <ul className="links-vertical">
                                        <li>
                                            <Link to={'/charbonneurs/'}>
                                                Charbonneurs
                                            </Link>
                                        </li>
                                        <li>
                                            <Link to={'/condition_utilisation/'}>
                                                Terme et conitions
                                            </Link>
                                        </li>
                                        <li>
                                            <Link to={'/confidentialité/'}>
                                                Politique de confidentialité
                                            </Link>
                                        </li>
                                        <li>
                                            <Link to={'/notice_legale/'}>
                                                Notice légale
                                            </Link>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div className="col-md-5">
                                <div className="column">
                                    <h4 className="mb-4">Newsletter</h4>
                                    <ul className="links-vertical">
                                        <p>Ne vous mefiez pas abbonez vous a notre newsletter pour etre notifier a tout temp!</p>
                                        <form method="" action="">
                                            <div className="row">
                                                <div className="col-sm-8">
                                                    <div className="form-group">
                                                        <div className="input-group mb-4">
                                                            <div className="input-group-prepend">
                                                            <span className="input-group-text">
                                                                <i className="ni ni-email-83" /></span>
                                                            </div>
                                                            <input className="form-control" placeholder="votre Email..."
                                                                   type="text" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <div className="col-sm-4">
                                                    <button type="button" className="btn btn-primary btn-block">souscrivez
                                                    </button>
                                                </div>
                                            </div>
                                        </form>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr className="bg-white opacity-3" />
                    <div className="col-md-3 mx-auto">
                        <button type="button" className="btn-icon-only rounded-circle btn btn-facebook">
                            <span className="btn-inner--icon">
                                <i className="fab fa-facebook"/>
                            </span>
                        </button>
                        <button type="button" className="btn-icon-only rounded-circle btn btn-twitter">
                            <span className="btn-inner--icon">
                                <i className="fab fa-twitter"/>
                            </span>
                        </button>
                        <button type="button" className="btn-instagram btn-icon-only rounded-circle btn">
                            <span className="btn-inner--icon">
                                <i className="fab fa-instagram"/>
                            </span>
                       </button>
                        <button type="button" className="btn-icon-only rounded-circle btn btn-pinterest">
                            <span className="btn-inner--icon">
                                <i className="fab fa-pinterest"/>
                            </span>
                        </button>
                    </div>
                </div>
                <div className="copyright d-flex justify-content-center mt-4 mr-40">
                    Copyright &copy; {1900 + new Date().getYear()}, Designed by{" "}. Realized by
             <a href="/" className="title-red pl-2" style={{color: "red"}}> KazouGroup srl</a>
                </div>
            </footer>
        )
    }
}
export default FooterUserSite;
