// resources/js/components/inc/user/NavUserSite.vue
<template>
    <div>
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="/">
                    Kazoutech
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->


                        <template v-if="guest">
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                   Demander un service
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    Devenir un bosseur
                                </a>
                            </li>

                            <li class="nav-item">
                                <router-link  :to="{ name: 'login' }" class="nav-link">
                                    Connexion
                                </router-link>
                            </li>

                            <li class="nav-item">
                                <router-link  :to="{ name: 'register' }" class="nav-link">
                                    Inscription
                                </router-link>
                            </li>
                        </template>
                        <li v-else="guest" class="dropdown nav-item">
                            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" style="position: relative; padding-left: 50px;">
                                <img :src="userData.avatar" :alt="userData.name"  class="img-raised rounded-circle img-fluid text-center" style="width: 32px; height: 32px; position: absolute; top: 10px; left: 10px; border-radius: 50%"> <b v-text="userData.name"></b>
                            </a>
                            <div class="dropdown-menu dropdown-with-icons">
                                <a href="#" class="dropdown-item">
                                   <b>Dashboard</b>
                                </a>
                                <a href="#" class="dropdown-item">
                                    <b>Profile</b>
                                </a>
                                <a href="#" class="dropdown-item">
                                    <b>Paramètres</b>
                                </a>
                                <a href="javascript:void(0)" @click="navLogout()" class="dropdown-item">
                                    <b>Deconnexion</b>
                                </a>
                            </div>
                        </li>
                        <!--<li class="nav-item">
                            <router-link  :to="{ name: 'contact_cm' }" class="nav-link">
                                Contact
                            </router-link>
                        </li>-->
                    </ul>
                </div>
            </div>
        </nav>

    </div>
</template>

<script>
    export default {
        data() {
            return {
                userData: {},
            }
        },
        methods: {

            /* ***** script logout navbar ****/
            navLogout(){
                //Start Progress bar
                this.$Progress.start();

                //Envoyer la requet au server
                axios.post('/logout').then(() => {

                    location.replace(`/`);
                    //End Progress bar
                    this.$Progress.finish();
                }).catch(() => {
                    //Failled message
                    this.$Progress.fail();
                });
            },
        },
        created() {
            axios.get("/api/account/user").then(
                response => {this.userData = response.data.data}
            );
            //setInterval(() => this.loadItems(),3000);
        }
    }
</script>

<style scoped>

</style>

// resources/js/reactjs/components/inc/NavUserSIte.jsx
import React, {Component} from "react";
import {Link, NavLink} from 'react-router-dom';

class NavUserSIte extends Component {
    constructor(props) {
        super(props);
        this.state = {};
        this.navLogout = this.navLogout.bind(this);
    }

    navLogout(e) {
        axios.post('/logout')
            .then(() => {
                window.location.reload();
            }).catch(() => {
            //
        });
    }

    render() {

        return (
            <nav className="navbar navbar-expand-md fixed-top navbar-transparent " color-on-scroll="400">
                <div className={'container'}>
                    <Link to={'/'} className="navbar-brand mr-lg-5">
                        <img src=".." alt={'Kazoutech'}/>
                    </Link>
                    <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global"
                            aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"/>
                    </button>
                    <div className="navbar-collapse collapse" id="navbar_global">
                        <div className="navbar-collapse-header">
                            <div className="row">
                                <div className="col-6 collapse-brand">
                                    <a href="/">
                                        <img src="/assets/img/vendor_site/brand/blue.png"/>
                                    </a>
                                </div>
                                <div className="col-6 collapse-close">
                                    <button type="button" className="navbar-toggler" data-toggle="collapse"
                                            data-target="#navbar_global" aria-controls="navbar_global"
                                            aria-expanded="false" aria-label="Toggle navigation">
                                        <span></span>
                                        <span></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                        <ul className="navbar-nav navbar-nav-hover align-items-lg-center ml-lg-auto">
                            <li className={'nav-item'}>
                                <Link to={'/occupations/'} className="nav-link" role="button">
                                    <i className="ni ni-app d-lg-none"/>
                                    <span className="nav-link-inner--text"><b>Demander un service</b></span>
                                </Link>
                            </li>
                            {$guest ?
                                <>
                                    <li className={'nav-item'}>
                                        <a href={'/devenir_charbonneur/'} className="nav-link" role="button">
                                            <i className="ni ni-app d-lg-none"/>
                                            <span className="nav-link-inner--text">
                                                <b>Dévenir charbonneur</b>
                                            </span>
                                        </a>
                                    </li>
                                    <li className="nav-item">
                                        <a href="/login" className="btn btn-default">
                                            <span className="btn-inner--icon">
                                               <i className="ni ni-check-bold"/>
                                           </span>
                                            <span className="nav-link-inner--text pt-40 position-navbar"><b>Connexion</b></span>
                                        </a>
                                    </li>
                                    <li className="nav-item">
                                        <a href="/register" className="btn btn-outline-primary">
                                           <span className="btn-inner--icon">
                                               <i className="ni ni-circle-08"/>
                                           </span>
                                            <span className="nav-link-inner--text pt-40 position-navbar">Inscription</span>
                                        </a>
                                    </li>
                                </>
                                :
                                <li className="nav-item dropdown">
                                    <a href=".." className="nav-link" data-toggle="dropdown" role="button">
                                        <span><img src={$userKazou.avatar} className="avatar"/></span>
                                        <span className="nav-link-inner--text"><b>{$userKazou.name}</b></span>
                                    </a>
                                    <div className="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        {$userKazou.my_status === 'active' && (
                                            <a href="/dashboard" className="dropdown-item">
                                                <i className="ni ni-building text-muted"/>
                                                Dashboard
                                            </a>
                                        )}
                                        <Link to={`/user/profile/edit/`} className="dropdown-item">
                                            <i className="ni ni-lock-circle-open text-muted"/>
                                            Editer mon profile
                                        </Link>
                                        <Link to={`/charbonneur/${$userKazou.username}/`} className="dropdown-item">
                                            <i className="ni ni-circle-08 text-success"/>
                                            Mon profile
                                        </Link>
                                        <a className="dropdown-item" onClick={() => this.navLogout()}>
                                            <i className="ni ni-atom text-info"/>
                                            Déconnexion
                                        </a>
                                    </div>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        )
    }
}

export default NavUserSIte;
